import React from "react";
import styles from "./Layout.module.css";
import Navbar from "./Navbar/Navbar";
import Head from "next/head";

interface Props {
	children: React.ReactNode
}

const Layout: React.FunctionComponent<Props> = (props: Props) => {

	//authUser and loading to auto direct to login?
	
	return (
		<>
		<div className={styles.container}>
      {/* <Head> */}
        {/* <title>{title}</title> */}
        {/* <meta name="description" content="Generated by create next app" /> */}
        {/* <link rel="icon" href="/favicon.ico" /> */}
      {/* </Head> */}
			{/* <div className={styles.navbar}> */}
			<Navbar />
			{/* </div> */}
			<div className={styles.page}>
				{props.children}
			</div>
		</div>
		</>
	)
}

export default Layout;